# -*- coding: utf-8 -*-
"""HTML_Quick_Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beVrj-_6gJkjliW-QctCHwwpTIGFbC3c
"""

!pip install gradio transformers accelerate torch

custom_css = """
body {
    background-color: #0f172a !important;
}

.gradio-container {
    background-color: #0f172a !important;
    color: white !important;
}

button {
    background: #f97316 !important;
    color: white !important;
    border-radius: 8px !important;
}

textarea, input {
    background-color: #1e293b !important;
    color: white !important;
    border: 1px solid #334155 !important;
}

.tab-nav button {
    color: white !important;
}
"""

class ColorPaletteGenerator:

    def __init__(self):
        self.palettes = {
            "modern": ["#6366f1", "#4f46e5", "#0f172a", "#f8fafc"],
            "vibrant": ["#ec4899", "#db2777", "#111827", "#f3f4f6"],
            "ocean": ["#0ea5e9", "#0369a1", "#0c4a6e", "#e0f2fe"],
            "forest": ["#16a34a", "#166534", "#052e16", "#dcfce7"],
            "sunset": ["#f97316", "#ea580c", "#7c2d12", "#fff7ed"],
            "luxury": ["#d4af37", "#b8860b", "#111111", "#f5f5dc"],
            "creative": ["#a855f7", "#7e22ce", "#1e1b4b", "#ede9fe"],
            "minimal": ["#374151", "#1f2937", "#ffffff", "#111827"]
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

def build_html(title, description, colors):

    primary, secondary, background, text = colors
    desc = description.lower()
    sections_html = ""

    # HERO
    if "hero" in desc:
        sections_html += f"""
        <header id="home" class="hero">
            <h1>Welcome to {title}</h1>
            <p>Create amazing web experiences</p>
            <a href="#contact" class="btn">Get Started</a>
        </header>
        """

    # FEATURES
    if "features" in desc:
        sections_html += """
        <section id="features" class="section">
            <h2>Features</h2>
            <div class="features-grid">
                <div class="card">🚀 <h3>Fast Performance</h3></div>
                <div class="card">🔒 <h3>Secure</h3></div>
                <div class="card">⚡ <h3>Easy to Use</h3></div>
            </div>
        </section>
        """

    # PRICING
    if "pricing" in desc:
        sections_html += """
        <section id="pricing" class="section">
            <h2>Pricing Plans</h2>
            <div class="features-grid">
                <div class="card">Basic - $9/month</div>
                <div class="card">Pro - $29/month</div>
                <div class="card">Enterprise - $99/month</div>
            </div>
        </section>
        """

    # CONTACT
    if "contact" in desc:
        sections_html += """
        <section id="contact" class="section">
            <h2>Contact Us</h2>
            <div class="contact-form">
                <input placeholder="Your Name">
                <input placeholder="Your Email">
                <button class="btn">Send Message</button>
            </div>
        </section>
        """

    # FOOTER
    if "footer" in desc:
        sections_html += f"""
        <footer>
            © 2026 {title} | All Rights Reserved
        </footer>
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style>
            html {{
                scroll-behavior: smooth;
            }}

            body {{
                margin: 0;
                font-family: Arial, sans-serif;
                background: {background};
                color: {text};
            }}

            nav {{
                position: sticky;
                top: 0;
                background: #111;
                padding: 15px 30px;
                display: flex;
                justify-content: space-between;
                align-items: center;
                z-index: 1000;
            }}

            nav a {{
                color: white;
                text-decoration: none;
                margin-left: 20px;
            }}

            .hero {{
                padding: 120px 20px;
                text-align: center;
                background: linear-gradient(135deg, {primary}, {secondary});
                color: white;
            }}

            .section {{
                padding: 80px 20px;
                text-align: center;
            }}

            .features-grid {{
                display: flex;
                justify-content: center;
                gap: 20px;
                flex-wrap: wrap;
                margin-top: 30px;
            }}
.card {
    background: #f8fafc;
    color: #111;
    padding: 25px;
    border-radius: 10px;
    min-width: 220px;
    box-shadow: 0 8px 20px rgba(0,0,0,0.15);
    transition: transform 0.3s ease;
}

.card:hover {
    transform: translateY(-8px);
}

            .btn {{
                display: inline-block;
                margin-top: 20px;
                padding: 12px 24px;
                background: white;
                color: black;
                text-decoration: none;
                border-radius: 6px;
                font-weight: bold;
            }}

            footer {{
                background: #111;
                color: white;
                padding: 20px;
                text-align: center;
                margin-top: 40px;
            }}

        </style>
    </head>

    <body>

        <nav>
            <div><strong>{title}</strong></div>
            <div>
                <a href="#home">Home</a>
                <a href="#features">Features</a>
                <a href="#pricing">Pricing</a>
                <a href="#contact">Contact</a>
            </div>
        </nav>

        {sections_html}

    </body>
    </html>
    """

    return html

palette_generator = ColorPaletteGenerator()

def generate_site(title, description, style):

    colors = palette_generator.get_palette(style)
    html = build_html(title, description, colors)

    return html, html

import gradio as gr

with gr.Blocks(css=custom_css, theme=gr.themes.Base()) as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler Advanced")
    gr.Markdown("### Professional HTML Page Generator with Auto-Styling")

    with gr.Tabs():

        # TAB 1: Generate Page
        with gr.Tab("Generate Page"):

            with gr.Row():
                with gr.Column():
                    title = gr.Textbox(label="Page Title")
                    desc = gr.Textbox(label="Page Description & Sections")
                    style = gr.Dropdown(
                        ["modern","vibrant","ocean","forest",
                         "sunset","luxury","creative","minimal"],
                        label="Color Style"
                    )
                    btn = gr.Button("🔥 Generate HTML")

                with gr.Column():
                    code_output = gr.Code(label="Generated HTML", language="html")

        # TAB 2: Live Preview
        with gr.Tab("Live Preview"):
            preview = gr.HTML()
            load_btn = gr.Button("Load Preview")

        # TAB 3: Color Palettes
        with gr.Tab("Color Palettes"):
            palette_style = gr.Radio(
                ["modern","vibrant","ocean","forest",
                 "sunset","luxury","creative","minimal"],
                label="Choose Style"
            )
            palette_output = gr.Textbox(label="Palette Colors")

        # TAB 4: Templates
        with gr.Tab("Templates"):
            gr.Markdown("### Quick Templates")
            gr.Markdown("""
            • Portfolio Website
            • SaaS Landing Page
            • Company Website
            """)

        # TAB 5: Guide
        with gr.Tab("Guide"):
            gr.Markdown("""
            ## How It Works

            1. Enter Title
            2. Enter Description
            3. Select Color Style
            4. Click Generate
            5. Preview your page
            """)

    # Button Functions
    btn.click(generate_site, inputs=[title, desc, style],
              outputs=[preview, code_output])

    load_btn.click(generate_site, inputs=[title, desc, style],
                   outputs=[preview, code_output])

    palette_style.change(
        lambda x: palette_generator.get_palette(x),
        inputs=palette_style,
        outputs=palette_output
    )

demo.launch(share=True)